### ISSUE TITLE
Error al conectarse despues de poner el server en marcha

### ISSUE THREAD

**Issue by Chichimokers** [luskaner/aoe2DELanServer#28]
Using config file: G:\Ernes\Juegos\Age of Empire 2 Definitive Edition\aoe2DELanServer_launcher_1.2.2_win_x86-64\resources\config.ini
Setting up...
Waiting 15 seconds for server announcements on LAN on port(s) 31978 (we are v. 0), you might need to allow 'launcher.exe' in the firewall...
Found a single server "100.102.44.49, 127.0.0.1, 192.168.43.251 (DESKTOP-80G0OS0) - v. 0", will connect to it...
Server is not reachable. Check the client can connect to  on TCP port 443 (HTTPS)
Program finished successfully, closing in 10 seconds...

**Comment by luskaner** [comment]
Hello:

Have you tried connecting to the server manually? You may do so trying to connect to:

* https://100.102.44.49
* https://127.0.0.1
* https://192.168.43.251

Please check the 3 and report back =)
Also, it may be a firewall issue, try turning it off (you may of course ensure both 3 networks are marked as private - not public - and/or adding an exception)

Plus, can you attach the latest log file from `server/logs` directory?

Thanks,

**Comment by Chichimokers** [comment]
yes i try connect to https://127.0.0.1/ and https://100.102.44.49/ sucefully but https://192.168.43.251/ i have warnig ssl certifacate i suceffuly connect after accept the risky  and the logs file are celean i dont have idea why PD:Hablo espa;ol

**Comment by Chichimokers** [comment]
![image](https://github.com/user-attachments/assets/f9cc064e-6b21-48f4-ad02-9bd0d63df41d)

**Comment by luskaner** [comment]
Vale:

Creo que el problema reside que a pese a que tiene 3 posibles direcciones IP a las que conectarse, intenta conectarse justo a la que no funciona. Esta claro que debería ser mas inteligente y puedo mejorarlo =) 
Como "workaround" puedes intentar poner en el Config.ini del launcher en el apartado de "[Server]", "Host" a 127.0.0.1 (pero claro eso solo funcionara para el pc donde el launcher y server residen en el mismo) y "Start" a "false".

**Comment by luskaner** [comment]
Tal como estas haciendo, con esa configuracion deberas iniciar el server a mano.

**Comment by Chichimokers** [comment]
yaya acabo de hacerlo es que tenia sofether vpn server en el puerto 443

**Comment by Chichimokers** [comment]
lo otro puedo usar un cliente de age of empire 2 definite edition de elamigos la pagina pirata

**Comment by luskaner** [comment]
Vale, perfecto, igualmente trataré de mejorar la conexión por el launcher, dejo la issue abierta.

**Comment by luskaner** [comment]
Te respondo por correo a lo último.

**Comment by Chichimokers** [comment]
gracias

**Comment by Chichimokers** [comment]
> Te respondo por correo a lo último.

ok developer1575@gmail.com
