### ISSUE TITLE
Offline Steam doesn't work!

### ISSUE THREAD

**Issue by MaMo7x** [luskaner/aoe2DELanServer#31]
I don't know if this should be considered an issue or not but here it is,
When the **steam** is running in **offline mode** the multiplayer game is not possible as it'll keep loading and displays "Please wait, communicating with Server".
![image](https://github.com/user-attachments/assets/3eca4ac7-3c0e-4745-9955-bc742d25806e)

**Comment by luskaner** [comment]
Hello:

This a limitation imposed by the game itself (not my server nor launcher). To bypass this limitation, unfortunately, you need to use an unofficial launcher (I cannot provide this in GitHub for legal reasons). Contact me private luskaner at gmail dot com for more details ;)
