### ISSUE TITLE
Server config.ini any other IP except 0.0.0.0 server won't start

### ISSUE THREAD

**Issue by binarybubble** [luskaner/aoe2DELanServer#4]
Running the server from commandline. If any IP other than 0.0.0.0 is entered in the \resources\config\config.ini. server won't start.

`panic: runtime error: index out of range [4] with length 4

goroutine 6 [running]:
server/ip.calculateBroadcastIp(...)
        /home/runner/work/aoe2DELanServer/aoe2DELanServer/server/ip/ip.go:22
server/ip.ResolveBroadcastIp({0x1a71590, 0x10, 0x10})
        /home/runner/work/aoe2DELanServer/aoe2DELanServer/server/ip/ip.go:57 +0x2b2
server/ip.Announce({0x1a71590, 0x10, 0x10})
        /home/runner/work/aoe2DELanServer/aoe2DELanServer/server/ip/announce.go:12 +0x5c
main.main.func1()
        /home/runner/work/aoe2DELanServer/aoe2DELanServer/server/main.go:31 +0x2c
created by main.main in goroutine 1
        /home/runner/work/aoe2DELanServer/aoe2DELanServer/server/main.go:30 +0x27a`

**Comment by binarybubble** [comment]
Announce needs to be false, then it works, but for my understanding "announce" should be true for clients to discover it?

**Comment by luskaner** [comment]
Hi

Thanks for reporting the bug, that seems a big issue. Your assumption is correct, if Announce is false then the users launcher needs to be configured to connect to a host/ip directly and will not auto-discover the server. But it is related as it will only announce on the interface that is listening to, which I think makes sense? 🤔

**Comment by luskaner** [comment]
Either way it should work, yes

**Comment by binarybubble** [comment]
Ah, I see. I'll test again set everything to manually. client and server.
It worked a few times, but the lobby disconnected after a few seconds.

**Comment by binarybubble** [comment]
ok. Works now like a charm. NICE, thx

**Comment by luskaner** [comment]
Perfect, anyway will make sure in 1.1.0 milestone there is no error =) and then close this
