### ISSUE TITLE
Launcher: Game not found

### ISSUE THREAD

**Issue by juancito06** [luskaner/aoe2DELanServer#50]
Hello, I don't know much about this, where should I put the path of my game in the config.ini of the launcher 1.4.0? I always get game not found

**Comment by luskaner** [comment]
In `resources/config.ini` (Launcher folder), you need to edit `[Client].Executable` to point to the main executable of the game such as "C:\AoE2DE\Game Launcher.exe" (you might need to use quotes). Try to inspect the folder or run the game in order to know which is the executable.

**Comment by juancito06** [comment]
I don't know what I'm doing wrong 
![Captura de pantalla 2024-10-14 212325](https://github.com/user-attachments/assets/f28336b6-9270-4197-b137-f888249f5a98)

**Comment by luskaner** [comment]
You are doing the reverse way, it should be:
`Executable = "C:\Games..."`
not:
`"C:\Games..." = auto`

If you have doubt about how the INI file format works please look at https://en.wikipedia.org/wiki/INI_file ;)

**Comment by juancito06** [comment]
ok, it works but now when I host a game I get this
![Captura de pantalla 2024-10-15 132116](https://github.com/user-attachments/assets/7f652eb1-7b25-4d47-93a8-8c11d0cbae3b)

**Comment by luskaner** [comment]
When creating the lobby you must select in Server (dropdown) "Use Local Lan Server" not the default option.

**Comment by juancito06** [comment]
ok it works, thanks

**Comment by luskaner** [comment]
Perfect, next time be sure to read [Troubleshooting](https://github.com/luskaner/aoe2DELanServer/wiki/Troubleshooting) page first as all is explained there ;)
